{
 "title": "SQLite vs LiteDB insert",
 "time": { "from": "now-37m", "to": "now" },
 "panels": [
  {
   "title": "dotnet_total_memory_bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "dotnet_total_memory_bytes" }
   ]
  },
  {
   "title": "Inserted objects",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 12, "y": 0 },
   "targets": [
    { "expr": "database_insert_object" }
   ]
  },
  {
   "title": "database_size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "database_size" }
   ]
  },
  {
   "title": "database_insert_object / sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(database_insert_object[5s])"
    }
   ]
  }
 ]
}